### ISSUE TITLE
Exception 'You do not have permission to view this repository' on scheduled workflow run

### ISSUE THREAD

**Issue by spier** [github/issue-metrics#166]
I have a workflow that runs on a monthly schedule to generate PR and Issue metrics.

When it ran on the schedule yesterday, it [failed](https://github.com/InnerSourceCommons/InnerSourcePatterns/actions/runs/6714828057/attempts/1) with this error:
> You do not have permission to view this repository; Check you API Token.

However when re-running the workflow again, it [succeeded](https://github.com/InnerSourceCommons/InnerSourcePatterns/actions/runs/6714828057).

Not sure if this was a blips in the matrix or what happened here :)

## For context: 

The workflow file is in the same repo for which metrics are generated. 
Therefore I believe I can use the default `secrets.GITHUB_TOKEN` token that is automatically generated for each workflow run.
Also the fact that the 2nd run succeeded seems to indicate that this is not a general permission issue.

**Comment by zkoppert** [comment]
Oh wow! That is surprising. My guess is that this is a glitch but will keep the issue open for now in case we get any other reports of the same thing.

**Comment by zkoppert** [comment]
Closing as we've not seen this again. Please re-open if spotted again.

**Comment by EricStG** [comment]
We have the same issue. In a schedule, we get:
```
Starting issue-metrics search...
Searching for issues...
You do not have permission to view this repository; Check you API Token.
```
But run it manually and every thing is fine

**Comment by zkoppert** [comment]
@EricStG can you confirm that the PAT you are using manually and in the action are the same?

Is your workflow referring to the default token or one in your repository secrets?

**Comment by EricStG** [comment]
@zkoppert We're using the default token, it's the same regardless on how we trigger the job

**Comment by zkoppert** [comment]
@EricStG I'd recommend setting up a Personal Access Token or App private key and ID. The default token in my understanding is unable to be granted cross repo permissions. Here are some docs with your options for setting those up: 
- See Step 5 listed here: https://github.com/github/issue-metrics?tab=readme-ov-file#use-as-a-github-action
- GitHub App authentication method: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/about-authentication-with-a-github-app
- GitHub Personal Access Token Method: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic

**Comment by zkoppert** [comment]
Interesting. Maybe I'm pulling on the wrong thread. Do you grant permissions in your workflow file?

**Comment by EricStG** [comment]
Yes, we grant `issues: write` and `pull-requests: read`

Here's the workflow
```yaml
name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: "repo:${{ github.repository }} is:pr is:merged closed:${{ env.last_month }} -author:app/renovate"
          HIDE_LABEL_METRICS: true
          HIDE_TIME_TO_ANSWER: true
```
