### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by paul-uz** [github/issue-metrics#53]
Can we get some better installation instructions?

I'm struggling to understand what exactly I need to do in order to use this action.

Step 1 states "Create a repository to host this GitHub Action or select an existing repository."

Do I fork this repo? Clone it then upload to me own account? Or if I select a pre-existing repo, is it the one I want to be scanned? 

Step 2 "Create the env values from the sample workflow below (GH_TOKEN, SEARCH_QUERY) with your information as repository secrets. More info on creating secrets can be found [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets). Note: Your GitHub token will need to have read access to the repository in the organization that you want evaluated"

Where do I put these env vars? I see an .env-example file, so I guess I need an .env file, but where would it go? In the repo I want scanning, or in some other repo (see issues with step 1)

**Comment by zkoppert** [comment]
Hi @paul-uz! Thanks for creating this issue! I agree we need some better instructions.

It's easiest in terms of setup if you use the repo that you want scanned as the repo where you run this action.

Here is an example: I'd like to get statistics on github.com/zkoppert/project-a and I would also like the resulting reports to be opened as issues in that repo. 
1. I go to the github.com/zkoppert/project-a repository
2. click on "add file"
3. I name the file at the top with the path for GitHub workflows and my specific file name: 
![Screenshot 2023-07-20 at 7 49 14 AM](https://github.com/github/issue-metrics/assets/6935431/b7ec9f43-d5ac-4f6f-8be4-c090325c0510)
4. I copy an example from the issue-metrics `README.md` file. I chose this one because I want to run the report monthly. 
```yaml
name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  issues: write

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    
    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Get the current date
        current_date=$(date +'%Y-%m-%d')

        # Calculate the previous month
        previous_date=$(date -d "$current_date -1 month" +'%Y-%m-%d')

        # Extract the year and month from the previous date
        previous_year=$(date -d "$previous_date" +'%Y')
        previous_month=$(date -d "$previous_date" +'%m')

        # Calculate the first day of the previous month
        first_day=$(date -d "$previous_year-$previous_month-01" +'%Y-%m-%d')

        # Calculate the last day of the previous month
        last_day=$(date -d "$first_day +1 month -1 day" +'%Y-%m-%d')

        echo "$first_day..$last_day"
        echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:owner/repo is:issue created:${{ env.last_month }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: <YOUR_GITHUB_HANDLE_HERE>
```
5. After I paste it in my browser, I change line 40 `SEARCH_QUERY: 'repo:owner/repo is:issue created:${{ env.last_month }} -reason:"not planned"'` to match the issues I want to get metrics on. I want metrics for all issues created last month so I change it to `SEARCH_QUERY: 'repo:zkoppert/project-a is:issue created:${{ env.last_month }}'`
6. Next I change line 47 `assignees: <YOUR_GITHUB_HANDLE_HERE>` to be ` assignees: zkoppert` since I want the metrics report issue to be assigned to me.
7. I commit the workflow file to the repo
![Screenshot 2023-07-20 at 7 59 48 AM](https://github.com/github/issue-metrics/assets/6935431/8abf388a-7326-41d1-9337-7274fc4bf419)
8. I can either wait for my workflow to run on the first day of the month, or I can navigate to `https://github.com/zkoppert/project-a/actions/workflows/metrics.yaml` and click the "Run Workflow button"
![Screenshot 2023-07-20 at 8 01 56 AM](https://github.com/github/issue-metrics/assets/6935431/733b8d0e-1453-4811-8cb5-2407a678e5a1)
9. Then after the workflow runs (time to complete will vary by repo), you should see an issue pop up in the repo like this one: https://github.com/zkoppert/project-a/issues

Hope that helps! I'll also work on improving the README documentation.

**Comment by paul-uz** [comment]
How do I create the GITHUB_TOKEN secret exactly?

**Comment by paul-uz** [comment]
> GITHUB_TOKEN should be automatically generated as a part of the GitHub action running. More info on that at https://docs.github.com/en/actions/security-guides/automatic-token-authentication. Is your workflow file in the same repository that you are running metrics on?
> 
> Could you post your workflow file?

I copied the workflow you posted and just changed the github user name to my own.

**Comment by zkoppert** [comment]
Here is the decision point on whether or not you need to generate your own token or use the built in one (called GITHUB_TOKEN):

If you are running this workflow in the same repository as the one that you are measuring and the issue with the metrics should also appear in that repository then you do not need to create your own token.

If you are running this workflow in a different repository from the one you are measuring or you want the resulting issue with the metrics in it to appear in a different repository, then you need to create your own token.

**Comment by paul-uz** [comment]
> With regards to the workflow file, you mentioned that you changed the github username. That's great! Did you also change the `SEARCH_QUERY`? Step 5 from [my list above](https://github.com/github/issue-metrics/issues/53#issuecomment-1644116610)?

No, I kept the search query the same. That wasn't the issue though, it's the token that's not working.

I'm running the action in the report I want to report on, but I get that validation error, so it seems the auto generated token isn't working?

**Comment by paul-uz** [comment]
> Here is the decision point on whether or not you need to generate your own token or use the built in one (called GITHUB_TOKEN):
> 
> If you are running this workflow in the same repository as the one that you are measuring and the issue with the metrics should also appear in that repository then you do not need to create your own token.
> 
> If you are running this workflow in a different repository from the one you are measuring or you want the resulting issue with the metrics in it to appear in a different repository, then you need to create your own token.

Can you provide succinct instructions on how to set up the 2nd type of token as well, please?

**Comment by zkoppert** [comment]
I've added instructions for the 2nd type of token in [this pull request](https://github.com/github/issue-metrics/pull/56/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R37). Let me know if you feel like something is missing there.

**Comment by zkoppert** [comment]
regarding the auto-generated token not working, do you have this in your workflow file:

```yaml
permissions:
  issues: write
```

**Comment by paul-uz** [comment]
> regarding the auto-generated token not working, do you have this in your workflow file:
> 
> ```yaml
> permissions:
>   issues: write
> ```

Yes, as its in the workflow i copied from you posted here.

I fixed the `repo:owner/repo` string in the search query, but i still get a validation error

Here is my file

```yml

name: Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  issues: write

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    
    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Get the current date
        current_date=$(date +'%Y-%m-%d')

        # Calculate the previous month
        previous_date=$(date -d "$current_date -1 month" +'%Y-%m-%d')

        # Extract the year and month from the previous date
        previous_year=$(date -d "$previous_date" +'%Y')
        previous_month=$(date -d "$previous_date" +'%m')

        # Calculate the first day of the previous month
        first_day=$(date -d "$previous_year-$previous_month-01" +'%Y-%m-%d')

        # Calculate the last day of the previous month
        last_day=$(date -d "$first_day +1 month -1 day" +'%Y-%m-%d')

        echo "$first_day..$last_day"
        echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo<OWNER/REPO_NAME_HERE> is:issue created:${{ env.last_month }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: paul-uz
```
